/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ExperimentsRouteImport } from './routes/experiments'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExperimentsIndexRouteImport } from './routes/experiments.index'
import { Route as ExperimentsNewRouteImport } from './routes/experiments.new'
import { Route as ExperimentsIdRouteImport } from './routes/experiments.$id'

const ExperimentsRoute = ExperimentsRouteImport.update({
  id: '/experiments',
  path: '/experiments',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperimentsIndexRoute = ExperimentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ExperimentsRoute,
} as any)
const ExperimentsNewRoute = ExperimentsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ExperimentsRoute,
} as any)
const ExperimentsIdRoute = ExperimentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ExperimentsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/experiments': typeof ExperimentsRouteWithChildren
  '/experiments/$id': typeof ExperimentsIdRoute
  '/experiments/new': typeof ExperimentsNewRoute
  '/experiments/': typeof ExperimentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/experiments/$id': typeof ExperimentsIdRoute
  '/experiments/new': typeof ExperimentsNewRoute
  '/experiments': typeof ExperimentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/experiments': typeof ExperimentsRouteWithChildren
  '/experiments/$id': typeof ExperimentsIdRoute
  '/experiments/new': typeof ExperimentsNewRoute
  '/experiments/': typeof ExperimentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/experiments'
    | '/experiments/$id'
    | '/experiments/new'
    | '/experiments/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/experiments/$id' | '/experiments/new' | '/experiments'
  id:
    | '__root__'
    | '/'
    | '/experiments'
    | '/experiments/$id'
    | '/experiments/new'
    | '/experiments/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExperimentsRoute: typeof ExperimentsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/experiments': {
      id: '/experiments'
      path: '/experiments'
      fullPath: '/experiments'
      preLoaderRoute: typeof ExperimentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiments/': {
      id: '/experiments/'
      path: '/'
      fullPath: '/experiments/'
      preLoaderRoute: typeof ExperimentsIndexRouteImport
      parentRoute: typeof ExperimentsRoute
    }
    '/experiments/new': {
      id: '/experiments/new'
      path: '/new'
      fullPath: '/experiments/new'
      preLoaderRoute: typeof ExperimentsNewRouteImport
      parentRoute: typeof ExperimentsRoute
    }
    '/experiments/$id': {
      id: '/experiments/$id'
      path: '/$id'
      fullPath: '/experiments/$id'
      preLoaderRoute: typeof ExperimentsIdRouteImport
      parentRoute: typeof ExperimentsRoute
    }
  }
}

interface ExperimentsRouteChildren {
  ExperimentsIdRoute: typeof ExperimentsIdRoute
  ExperimentsNewRoute: typeof ExperimentsNewRoute
  ExperimentsIndexRoute: typeof ExperimentsIndexRoute
}

const ExperimentsRouteChildren: ExperimentsRouteChildren = {
  ExperimentsIdRoute: ExperimentsIdRoute,
  ExperimentsNewRoute: ExperimentsNewRoute,
  ExperimentsIndexRoute: ExperimentsIndexRoute,
}

const ExperimentsRouteWithChildren = ExperimentsRoute._addFileChildren(
  ExperimentsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExperimentsRoute: ExperimentsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
